"""
Django settings for asoud project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import logging.config
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment with a safe fallback for local/dev only
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Force DEBUG=False in production
if os.environ.get('DJANGO_SETTINGS_MODULE') == 'config.settings.production':
    DEBUG = False

# Allowed hosts from env (comma-separated)
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

# Security: Ensure ALLOWED_HOSTS is not empty in production
# Note: This check is moved to production.py where ALLOWED_HOSTS is properly configured


# Application definition

INSTALLED_APPS = [
    # asgi
    'channels',
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'apps.base',
    'apps.core',
    'apps.category',
    'apps.cart',
    'apps.comment',
    'django_comments_xtd',
    'django_comments',
    'apps.gateway',
    'apps.information',
    'apps.market',
    'apps.item.apps.ItemConfig',
    'apps.region',
    'apps.users.apps.UsersConfig',
    'apps.discount',
    'apps.sms',
    'apps.reserve',
    'apps.price_inquiry',
    'apps.notification',
    'apps.flutter',
    'apps.market_subdomain',
    'apps.advertise',
    'apps.office_registration.apps.OfficeRegistrationConfig',
    'apps.analytics.apps.AnalyticsConfig',
    'apps.affiliate',
    'apps.payment',
    'apps.referral',
    'apps.wallet.apps.WalletConfig',
    'apps.chat.apps.ChatConfig',

    # Third-party apps
    'rest_framework',
]

# Use the custom user model defined in apps.users
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Re-enabled CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_hosts.middleware.HostsRequestMiddleware',  # disabled
    # 'django_hosts.middleware.HostsResponseMiddleware',  # disabled
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'
# ROOT_HOSTCONF = 'config.hosts'  # disabled
# DEFAULT_HOST = 'main'  # disabled

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

USE_SQLITE = os.environ.get('USE_SQLITE', 'false').lower() == 'true'

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME'),
            'USER': os.environ.get('DATABASE_USERNAME'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
            'HOST': os.environ.get('DATABASE_HOST', 'db'),
            'PORT': str(os.environ.get('DATABASE_PORT', '5432')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'config.validators.CustomPasswordValidator',
    },
]

# Custom Exception Handler - DISABLED FOR DEBUGGING
# REST_FRAMEWORK = {
#     'EXCEPTION_HANDLER': 'apps.core.exception_handler.custom_exception_handler',
#     'DEFAULT_RENDERER_CLASSES': [
#         'rest_framework.renderers.JSONRenderer',
#     ],
#     'DEFAULT_PARSER_CLASSES': [
#         'rest_framework.parsers.JSONParser',
#     ],
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'apps.users.authentication.JWTAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_THROTTLE_CLASSES': [
#         'rest_framework.throttling.AnonRateThrottle',
#         'rest_framework.throttling.UserRateThrottle'
#     ],
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '1000/hour',
#         'user': '10000/hour'
#     }
# }

# Enhanced Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {name} {module} {funcName} {lineno:d} {message}',
            'style': '{',
        },
        'security': {
            'format': 'SECURITY {levelname} {asctime} {name} {module} {funcName} {lineno:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        # Temporarily disabled file logging due to permission issues
        # 'file': {
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'level': 'INFO',
        #     'formatter': 'verbose',
        #     'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 10MB
        #     'backupCount': 5,
        # },
        # 'security_file': {
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'level': 'WARNING',
        #     'formatter': 'security',
        #     'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 10MB
        #     'backupCount': 10,
        # },
        # 'error_file': {
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'level': 'ERROR',
        #     'formatter': 'detailed',
        #     'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 10MB
        #     'backupCount': 10,
        # },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'config.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.inventory': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.payment': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Allow override via environment to avoid host-mount permission issues in dev
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', os.path.join(BASE_DIR, "static"))
# Using default StaticFilesStorage in base; set Manifest in production only.
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',
        'user': '10000/hour',
        'pin_create': '5/minute',
        'pin_verify': '10/minute',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Custom Exception Handler - NOW ENABLED for better error handling
    'EXCEPTION_HANDLER': 'apps.core.exception_handler.custom_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Asoud API',
    'DESCRIPTION': 'Unified Asoud API schema',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    'SWAGGER_UI_DIST': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

# (Removed duplicate LOGGING block; keeping the enhanced configuration above)

# Dictionary config
LANGUAGES = [
    ('en', _('English')),
    ('fa', _('Persian')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Configure channel layers (e.g., using Redis)
REDIS_HOST = os.environ.get('REDIS_HOST')
REDIS_USERNAME = os.getenv("REDIS_USERNAME")
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')
REDIS_PORT = os.environ.get('REDIS_PORT')

# Redis URL for caching
REDIS_URL = os.environ.get('REDIS_URL')
if not REDIS_URL and REDIS_HOST:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
elif not REDIS_URL:
    REDIS_URL = "redis://localhost:6379/0"

# Cache configuration
# try:
    # import django_redis
    # CACHES = {
    #     'default': {
    #         'BACKEND': 'django_redis.cache.RedisCache',
    #         'LOCATION': REDIS_URL,
    #         'OPTIONS': {
    #             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    #             'CONNECTION_POOL_KWARGS': {
    #                 'max_connections': 50,
    #                 'retry_on_timeout': True,
    #             },
    #             'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
    #             'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
    #         },
    #         'KEY_PREFIX': 'asoud',
    #     }
    # }
# except ImportError:
    # Fallback to default cache when django_redis is not available
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
 
# if REDIS_HOST:
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
#             "CONFIG": {
#                 "hosts": [(f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0")],
#             },
#         },
#     }
# else:
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}


# comments 
COMMENTS_APP = 'django_comments_xtd'
SITE_ID = 2
COMMENTS_XTD_MAX_THREAD_LEVEL = 1
COMMENTS_XTD_CONFIRM_EMAIL = False
COMMENTS_XTD_LIST_ORDER = ('-thread_id', 'order')

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://asoud.ir",
    "https://www.asoud.ir",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost",
    "http://127.0.0.1",
    "https://api.asoud.ir",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Disable django-hosts temporarily to fix routing (already disabled above)

# (Removed duplicate REST_FRAMEWORK block; keeping the primary one above)

# Subscription Configuration
SUBSCRIPTION_PLANS = {
    'monthly': {
        'name': 'Monthly Plan',
        'price': 29.99,
        'duration_days': 30,
        'features': [
            'Basic store setup',
            'Up to 100 products',
            'Basic analytics',
            'Email support',
        ]
    },
    'quarterly': {
        'name': 'Quarterly Plan',
        'price': 79.99,
        'duration_days': 90,
        'features': [
            'Advanced store setup',
            'Up to 500 products',
            'Advanced analytics',
            'Priority email support',
            'Custom domain',
        ]
    },
    'yearly': {
        'name': 'Yearly Plan',
        'price': 299.99,
        'duration_days': 365,
        'features': [
            'Premium store setup',
            'Unlimited products',
            'Premium analytics',
            'Phone & email support',
            'Custom domain',
            'Advanced customization',
            'Marketing tools',
        ]
    }
}

# Payment Gateway Configuration
PAYMENT_GATEWAYS = {
    'zarinpal': {
        'name': 'ZarinPal',
        'merchant_id': os.environ.get('ZARINPAL_MERCHANT_ID', ''),
        'sandbox': DEBUG,
    },
    'mellat': {
        'name': 'Mellat Bank',
        'terminal_id': os.environ.get('MELLAT_TERMINAL_ID', ''),
        'username': os.environ.get('MELLAT_USERNAME', ''),
        'password': os.environ.get('MELLAT_PASSWORD', ''),
        'sandbox': DEBUG,
    },
    'parsian': {
        'name': 'Parsian Bank',
        'pin': os.environ.get('PARSIAN_PIN', ''),
        'sandbox': DEBUG,
    }
}
